name: Trigger Jenkins CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Trigger Jenkins Job
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins
        uses: appleboy/jenkins-action@master
        with:
          url: "YOUR_JENKINS_URL"
          user: "YOUR_JENKINS_USERNAME"
          token: ${{ secrets.JENKINS_API_TOKEN }}
          job: "YOUR_JENKINS_PIPELINE_NAME"
